bs = float(input("enter basic salary:"))
hra_Per = float(input("enter HRA percentage:"))
da_per = float(input("enter DA percentage:"))
pf_per = float(input("enter PF percentage:"))
hra_amt = (bs * hra_Per)/100
da_amt = (bs * da_per)/100  
pf_amt = (bs * pf_per)/100
net_salary = bs + hra_amt + da_amt - pf_amt
print("basic salary=", bs)
print("HRA amount=", hra_amt)
print("DA amount=", da_amt)
print("PF amount=", pf_amt)
print("Net salary=", net_salary)